### ISSUE TITLE
We should rename all types ending in _t

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#103]
The POSIX standard actually reserves all type names ending in _t. The C standard only does that for things beginning in int and unit, but it seems like a good idea anyway.

We can use the _same_ name for the struct name, and the struct type. They are different namespaces and don't clash. My personal recommendation is to skip the _s / _t suffix completely. That would give us a struct definition that looks something like this:
```
   typedef struct tlv {
      ...
   } tlv;

**Comment by claucece** [comment]
After reading on several places, I'll say go ahead. 

Around, libgoldilocks, I'll say go ahead as well. Nevertheless, this is probably something libdecaf will also want, so I'll let Mike know ;)

Thanks!

**Comment by claucece** [comment]
Mmm the only concern I have it is that sometimes we have the same name for the variable and for the struct. For example: `k_ecdh` and `k_ecdh_t`. In these cases for example it will look work this:

From ` hash_update(hd, k_ecdh, sizeof(k_ecdh_t));` The sizeof was actually taking the size of the struct. 

to `hash_update(hd, k_ecdh, sizeof(k_ecdh));`...

**Comment by olabini** [comment]
Yeah, that will be annoying. I'll go ahead and name the structs _s instead. I'll also go ahead and add _p typedefs for the [1] examples, so you can use that when you want.

One point about your k_ecdh example is that I'm not sure the variable name in that case is actually very well chosen. The name should describe what it is, not the type of it. But yeah, that's a different problem.

I'll cover both libgoldilocks and libotr-ng with this issue.

**Comment by claucece** [comment]
> One point about your k_ecdh example is that I'm not sure the variable name in that case is actually very well chosen. The name should describe what it is, not the type of it. But yeah, that's a different problem

Yeah. It will be prob good to change it.

Thanks!
