### ISSUE TITLE
Check if we need other OTR Error messages

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#104]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using OTR errors.

## Reference

Please, refer to the [OTR Error Messages](https://github.com/otrv4/otrv4/blob/master/otrv4.md#otr-error-messages) section of the OTRv4 spec.

## Tasks
- Check: https://github.com/otrv4/libotr-ng/commit/5849d7cd578d1bdcfd365c27cb443e38a6feeaee#commitcomment-28687971
- Check: https://github.com/otrv4/libotr-ng/commit/dd0ec39067aad30bb746c2d9af376e72b9c2d9fb#commitcomment-28687990
- Check: https://github.com/otrv4/libotr-ng/commit/d654eec433807fe664e8f74116e8189257ecd026#commitcomment-28688119

## Open questions
- Should we include more error types?

**Comment by olabini** [comment]
Yes, I definitely think so.

**Comment by claucece** [comment]
Ok, so libotr3 has:

```
- OTRL_ERRCODE_ENCRYPTION_ERROR: occured while encrypting a message
- OTRL_ERRCODE_MSG_NOT_IN_PRIVATE: sent encrypted message to somebody who is not in a
 mutual OTR session
- OTRL_ERRCODE_MSG_UNREADABLE: sent an unreadable encrypted message
- OTRL_ERRCODE_MSG_MALFORMED: message sent is malformed
```

I think we can use the same..

**Comment by claucece** [comment]
Only a test and to update the spec is missing on this.
