### ISSUE TITLE
Correctly debug segmentation faults

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#105]
## Why

A library should be able to correctly debug itself. 

## Reference

- [How to debug a GCC segmentation fault](https://gcc.gnu.org/bugs/segfault.html)

## Tasks
- [ ] Correctly debug

**Comment by olabini** [comment]
I'm not sure I know what this means. I also don't know why I was assigned to it! =)

**Comment by claucece** [comment]
well, @olabini , this was something you mentioned on a call that will be nice to have. Manly this will try to add a nice way to debug the segmentation faults.. do you remember? ;)

**Comment by olabini** [comment]
Hmmmmmmmm. Ah, I think this was actually that we should have a debug-build that contains the debug symbols as well, so you can get good outputs from segfaults. Nothing to assign me to do right now, though.

**Comment by claucece** [comment]
Ok, unassigned :)
