### ISSUE TITLE
Remove attached encrypted message from non-interactive-auth message

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#109]
## Why

What is currently implemented does not match the spec

## Reference

otrv4/otrv4#151

## Tasks
- [x] Remove all the related fields
- [ ] Send a data message (heartbeat or with cipher-text) when the non-interactive DAKE finishes

**Comment by claucece** [comment]
Basically, done. But we need to test. If someone else wants to do that, go ahead ;)

**Comment by claucece** [comment]
@juniorz This is done, in the sense that we need a data msg to start the non-interactive dake. See: https://github.com/otrv4/libotr-ng/commit/8504c76b47aa50a03717de6b460fe9be8fa86cf9 I'm still waiting for a discussion with Ola around this.

**Comment by olabini** [comment]
I think we are clear on this. We will open a new issue once we hear back from Nik about it.
