### ISSUE TITLE
Not clear 2 websites, gitlab, github

### ISSUE THREAD

**Issue by Neustradamus** [twstrike/libotrv4#111]
Hello,

There are some problems for OTR:
- https://otr.cypherpunks.ca/
- http://otr.im/
- https://bugs.otr.im/explore

It is possible to redirect the old website (and all pages) to http://otr.im/ and add missing parts if there are?

See for the gitlab "bugs.otr.im".

It will be nice to update the old github to 4.1.1 and archive the deposit and inform to move it.
- https://github.com/off-the-record/libotr

Archive too? and redirect?
- https://bugs.otr.im/lib/libotr

**Comment by olabini** [comment]
Hi. This is the issues tracker for the next generation implementation of libotr. Your comments here have no relevance to that goal - and you have posted this message at several different places already.
