### ISSUE TITLE
Add callbacks

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#112]
## Why

We need the client to be aware of some things. 

## Tasks
We should consider adding callbacks for
- maximum message size 
- error messages
- session expiration
- instance tag

**Comment by juniorz** [comment]
I believe we need clarification in what we want to achieve. This seems to come from comparing what libotr has with what libotr-ng has., but they have different architectures. I don't think we need callbacks for everything libotr has.

I am creating a new issue to explain more about this (maybe it will serve as an onboarding material to the work on the plugin).

**Comment by claucece** [comment]
Yes, I agree.. we already sort of discussed around this on the last call. I guess the only thing from that list that we decided to make a callback was the session expiration. 

> I am creating a new issue to explain more about this (maybe it will serve as an onboarding material to the work on the plugin).

Thanks!

**Comment by claucece** [comment]
Thinking this again, I don't we need any. Closing this.
