### ISSUE TITLE
Check for thread safety

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#115]
## Why

A library has to be secure in the ways it handles threads.

## Tasks
- [ ] Check that is thread safe

**Comment by olabini** [comment]
I'll take a look and investigate this.

**Comment by olabini** [comment]
Specifically, this relates to identifying and documenting what can be safely modified from more than one thread, and what can not. In general, we don't have to be thread safe - we can just make sure that the client knows that they are in charge of synchronizing.
