### ISSUE TITLE
Decide to use the notif or the warning

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#121]

**Comment by claucece** [comment]
We are going for warnings on this.

**Comment by olabini** [comment]
This refactoring still needs to be implemented, right?

**Comment by claucece** [comment]
Yes.. in fact, we are missing to make the notification actually work. As they are not pointers, they are not really retaining value.

**Comment by olabini** [comment]
OK. I can take a look at that and implement it during the week.

**Comment by olabini** [comment]
Wait, I'm a bit confused here. You are saying we are going with warnings - so we are going to remove otrng_notif, correct?

**Comment by claucece** [comment]
Yeah.. forget my comment ;)

**Comment by olabini** [comment]
The one about fixing notifications, correct? =)

**Comment by claucece** [comment]
Yes @olabini
