### ISSUE TITLE
Associate DSA pubkey to the client profile and API for transitional signature (sign/verify)

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#124]
- [x] Add DSA key to client profile, serialize, deserialize.
- [x] Change client profile validation to optionally verify the transitional signature.
- [x] Add API to add a transitional signature to a client profile.
- [x] Add API to add a DSA pubkey to a client profile without signing (see discussion in otrv4/otrv4#167).

**Comment by giovaneliberato** [comment]
Related to https://github.com/otrv4/otrv4/issues/167
