### ISSUE TITLE
Add fallback behavior when receiving a non-interactive auth message

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#125]
When a user receives a non-interactive auth message they must first use their latest non-expired profiles to verify the received message. If the verification fails they should fallback to their previous non-expired profiles.

This is because the non-interactive auth message has no profile IDs anymore.

Tasks:

- [x] Remove ID from prekey profile.
- [x] Remove both profile IDs from the non-interactive auth message.
- [x] Implement fallback behavior for both prekey and client profiles.

**Comment by giovaneliberato** [comment]
Relates to https://github.com/otrv4/otrv4/issues/166

**Comment by claucece** [comment]
This is still missing to ' Implement fallback behavior for both prekey and client profiles.', right?

**Comment by juniorz** [comment]
Yes, it is missing.

Note that we still only stores the latest profile in the user state, and we only serialized the latest profile on the "otr4.client_profile" file.

**Comment by claucece** [comment]
On this:

- We should also take the forging key from the expired client profile
- We should also take the shared prekey from the expired prekey profile

**Comment by claucece** [comment]
Just tested this: it creates the file and it works. Must be further testing when the persistent architecture is done. For now, this is closed.
