### ISSUE TITLE
Safely delete old ratchet keys

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#13]

**Comment by juniorz** [comment]
After reverting 42711dd, 8073f69 and 7ea7071 (in this order) the test added in bb3aa342fd837acfdb75a2b663b18a5307dc5c0a works.

**Comment by natalieesk** [comment]
- [x] Securely delete DH private keys as soon as they're not needed any more
- [x] Same for ECDH

**Comment by natalieesk** [comment]
Deletion of the DH keys maybe contributing to the flaky memory leaks as referenced in #39 <- to look into
