### ISSUE TITLE
Should we read the private keys, instance tags and fingerprints for v3?

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#132]
As it was commented here:

// TODO: @client Read privkeys, fingerprints, instance tags for v3	
// To read stored private keys:	
//	
//    otrl_privkey_read(user_state, privkeyfilename);	
//	
// To read stored instance tags:	
//	
//    otrl_instag_read(user_state, instagfilename);	
//	
//        To read stored fingerprints:	
//	
//    otrl_privkey_read_fingerprints(user_state, fingerprintfilename,	
//            add_app_info, add_app_info_data);	
//	
//	
// tstatic int v3_privkey_generate(otrng_client_s *client, FILE *privf) {	
//   return otrl_privkey_generate_FILEp(client->state->user_state, privf,	
//                                      client->state->account_name,	
//                                      client->state->protocol_name);	
//}	
//	
// tstatic int v3_instag_generate(otrng_client_s *client, FILE *privf) {	
//   return otrl_instag_generate_FILEp(client->state->user_state, privf,	
//                                     client->state->account_name,	
//                                     client->state->protocol_name);

**Comment by olabini** [comment]
Instance tags not relevant, since we do use the same file
- This issue is just to make sure we are actually reading it into the libotr library.

**Comment by olabini** [comment]
This is fixed with the previous fingerprint work.
