### ISSUE TITLE
Ensure that we check the return value always

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#135]
Most importantly malloc() but also strdup() and other similar functions.

**Comment by claucece** [comment]
Should we check this over the tests as well?

**Comment by olabini** [comment]
I don't think that's super helpful, personally.

**Comment by olabini** [comment]
Both in pidgin plugin and libotr-ng. Also check returns from libgcrypt and other things.

**Comment by claucece** [comment]
I'm opening one as well for the plugin, as there it is mostly not checked.
