### ISSUE TITLE
Have export functionality for long term key

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#137]
See https://bugs.otr.im/lib/libotr/issues/28

**Comment by claucece** [comment]
Mmm.. I thought we were going for a 'no' on this, as the Client Profile is for example only for device.. should we rethink this?

**Comment by olabini** [comment]
Sure, not talking about client profile. More about the long term keys and so on. See the referenced issue for more info.

**Comment by claucece** [comment]
Ok. So it will be only one portion of the persisted info.

**Comment by claucece** [comment]
Ok, so looking at the issue I see that this will only be from the longterm key material. I don't see why we will export anything else...

**Comment by olabini** [comment]
So, I think functionality for this would need to export the private long term key AND the public forger key - assuming you want to make it possible to have the same fingerprint in different places. 

I'll assign this to me, come up with a standard format and put together APIs for it.
