### ISSUE TITLE
Review Joseph Birr-Pixton blogpost

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#138]
See https://bugs.otr.im/lib/libotr/issues/51 in the context of libotr-ng

**Comment by claucece** [comment]
I liked some suggestions of it, like:

* Unchecked fprintfs
* void otrl_mem_clear(volatile void *ptr, size_t len)
* http://cwe.mitre.org/data/definitions/14.html

The rest, I guess, are unchecked malloc and strup, overflow, etc.

**Comment by olabini** [comment]
We already have #141 for the second two. We should add a new issue for checking xprintf returns and close this issue.

**Comment by claucece** [comment]
@olabini just created. Thanks!
