### ISSUE TITLE
Extract memory cleaning behavior so we can customize with the safest options available

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#141]
See https://bugs.otr.im/lib/libotr/issues/108

**Comment by claucece** [comment]
We were already using sodium_mem_zero or something like that for this, I think.

**Comment by olabini** [comment]
Yeah, but I think it would be good to make sure we can use better options for different platforms, etc. If sodium_mem_zero doesn't turn out to be the right option, for example.

**Comment by claucece** [comment]
As far as I know this was already mapped. But we can map it again.
