### ISSUE TITLE
Build error because of -Werror=null-dereference

### ISSUE THREAD

**Issue by mytbk** [twstrike/libotrv4#144]
In https://github.com/otrv4/libotr-ng/blob/master/src/list.c#L29 list_new() can return NULL, so there's the following warning:

```
list.c: In function 'otrng_list_copy':
list.c:99:16: error: potential null pointer dereference [-Werror=null-dereference]
     copy->next = NULL;
```

The code should check the return value of list_new(), or terminate when malloc fails.

**Comment by claucece** [comment]
Fixed. Thanks!
