### ISSUE TITLE
Implement ALLOW_V3 policy flag

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#145]
The ALLOW_V3 policy means that libotr-ng will allow start a DAKE with v3 if v4 is not possible, or not allowed and the peer indicates that they support v3. In the other direction, ALLOW_V3 should be checked if we receive a v3 DAKE message. Refer to the state machine in the spec for the exact details.

This story also involves figuring out exactly where this flag should be configured in the Pidgin plugin.

**Comment by claucece** [comment]
Closed with 4ab07f150bc1134a7b7ed04cc2fc8f2ee3e60d70
