### ISSUE TITLE
Implement ALLOW_V4 policy

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#146]
The ALLOW_V4 policy means that libotr-ng will allow the start of a DAKE with v4, when the peer indicates that they support v4. In the other direction, ALLOW_V4 should be checked if we receive a v4 DAKE message. Refer to the state machine in the spec for the exact details.

This story also involves figuring out exactly where this flag should be configured in the Pidgin plugin - and doing it.

**Comment by claucece** [comment]
Closed with 4ab07f150bc1134a7b7ed04cc2fc8f2ee3e60d70
