### ISSUE TITLE
Implement SEND_WHITESPACE_TAG policy

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#148]
If this policy is turned on, automatically append the whitespace tag to outgoing plaintext messages.
This should also be configurable in the Pidgin UI.

**Comment by claucece** [comment]
Ok, this one is weird in the current way we have structured the code. In otrv3, this happened when you were on the state 'MSGSTATE_PLAINTEXT' (which can be reached when sending a TLV disconnected only) and tried to send a plaintext. This could happen as there was only one function that sends all messages (query, encrypted, and plaintext).

In the current structure, we have different ways to send messages (one for query, one for encrypted, none for plaintext). The only way we can reach this is again if we are on state 'START' (which can be reached when sending a TLV disconnected only) and tried to send a plaintext. I'm not sure if we are going to ever reach this.

**Comment by claucece** [comment]
Solved now :)
