### ISSUE TITLE
Add fragmentation

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#15]

**Comment by tdruiva** [comment]
Some thoughts from integration with OTRv3....

When we receive a message and this is fragmented, we should reconstruct it and if the protocol's running instance is OTRv3, just call receive_message.

In the case to sent a message, OTRv3 should prepare the message and OTRv4 fragment it if requested

**Comment by claucece** [comment]
Tani, this checks also:

On receiving fragments, check if

the recipient's own instance tag does not match the listed receiver instance tag
the listed receiver instance tag is not zero

**Comment by tdruiva** [comment]
Yeahh... is still missing this check... Tks! 
I'll do it (was in my mental notes)
