### ISSUE TITLE
Implement REQUIRE_INTERACTIVE policy

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#151]
If this policy is turned on, the library will not start a DAKE using non-interactive auth - it will only allow for DAKEZ and online conversation initiation.
This should be possible to configure in the UI as well.

(There is a question here about what we do if we RECEIVE a non-interactive auth. Do we drop it? Should we have a different policy for that? This should be investigated and decided).
(Another question is whether we should have policies for whether to publish prekey messages and other things, or if that behavior is controlled some other way)

**Comment by claucece** [comment]
> (There is a question here about what we do if we RECEIVE a non-interactive auth. Do we drop it? Should we have a different policy for that? This should be investigated and decided).

Mmm.. for me, you should be able to read it, but not use the same ratchet of this message to send offline messages. 

> (Another question is whether we should have policies for whether to publish prekey messages and other things, or if that behavior is controlled some other way)

If there is no non-interactive auth sending, then we should stop the publishing of prekey material, I guess.

**Comment by claucece** [comment]
Should be done now. Note that this policy will only affect the configuration fo whomever tries to send a message.
