### ISSUE TITLE
Implement TRY_DAKEZ_WHEN_OFFLINE policy

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#153]
When it looks like the peer is offline, the default behavior will be to start a non-interactive auth instead of an interactive one. However, because not all networks will be able to reliably tell you if the other party is offline, and people can be invisible etc, it might be worth sending an interactive DAKE as well, so that the other party can use the stronger DAKE if possible. If this policy is turned on, that will happen - otherwise only the non-interactive will happen.

This should be possible to configure in the UI.

(We might need another policy to govern whether we should respond to a DAKEZ when we are invisible.)

**Comment by claucece** [comment]
We do not agree with this policy anymore, as it seems to be defined for a specific messaging protocol. The behavior will be that when the party seems to be offline, an offline dake will be started.
