### ISSUE TITLE
Implement REQUIRE_AUTHENTICATED policy

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#154]
This policy means that we will only activate any of the OTR behavior when the other party is likely to be authenticated. This means that before starting a DAKE, if we have at least one trusted fingerprint for the peer, we should go ahead with the DAKE. AFTER the DAKE, we should also ensure that the key used was one we have a trusted fingerprint for. Otherwise we should abort the DAKE.
This should be configurable through the UI as well.

**Comment by claucece** [comment]
This depends on #28

**Comment by claucece** [comment]
Should be done now.
