### ISSUE TITLE
Implement simplified groups of policies

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#155]
Since we have many policies, it would be good to have a few groups of policies that go well together. See #14 for a few examples of these. For example:
```
- POLICY_NEVER
- POLICY_OPPORTUNISTIC
- POLICY_MANUAL
- POLICY_ALWAYS
- POLICY_DEFAULT 
- POLICY_HIGHEST_SEC 
- POLICY_OTRV4_FULL 
```
This needs to figure out which combinations of policies make sense together.

**Comment by olabini** [comment]
This depends on all the specifics policies being implemented, such as #145, #146, #147, #148 and so on.

**Comment by claucece** [comment]
The initial work for this is done; but we need to define the other policies to finish this. I'm leaving this for now.

**Comment by claucece** [comment]
The work of adding the group of policies has been done, and it relates to what OTRv3 had.
