### ISSUE TITLE
Refactor the pidgin plugin

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#16]
There are a few things we could probably remove, like:
- [ ] ConnContext. Remove the functions:
  - [ ] otrg_plugin_context_to_trust
  - [ ] otrg_plugin_conv_to_selected_context
  - [ ] conn_context_to_plugin_conversation
- [ ] Handle warnings

**Comment by tdruiva** [comment]
Do you think auto generate key is part of this refactoring or it can be a different task?

**Comment by juniorz** [comment]
#20 created ;)

**Comment by juniorz** [comment]
@tdruiva and I tried (and failed) to do it. It's hard to remove all the dependencies on libotr3 when the plugin has no tests.

I'm gonna close this because I don't want to encourage us to use more time on this.

**Comment by juniorz** [comment]
We know better what needs to be removed. Not that we want to remove them now.

**Comment by claucece** [comment]
For the moment, please, don't look at this issue. It should be moved once we move the work to the pidgin plugin.

**Comment by claucece** [comment]
This will only be reference as we have the appropriate issue on the pidgin plugin repo.
