### ISSUE TITLE
Setup coverity builds in travis-ci

### ISSUE THREAD

**Issue by DrWhax** [twstrike/libotrv4#161]
## Why

It would be nice to have  coverity builds once in a while. They recommend to setup a "coverity_scan" branch that has some extra stuff added to .travis-ci.yml (https://scan.coverity.com/travis_ci) like the token (that can be "encrypted" through a travis tool)

The master branch is also possible, however, coverity queue's your project in their open source pools and it can take a while before builds finishes and the analysis is done. So we should decide on what we want to do.

The current build I build with their toolchain and I uploaded the build manually.

https://scan.coverity.com/projects/libotr-ng (ask me or sofi for access)

We're still waiting to be accepted so we can see what the defects are :)

**Comment by DrWhax** [comment]
The limit we have is: 

> Up to 28 builds per week, with a maximum of 4 builds per day, for projects with fewer than 100K lines of code

**Comment by claucece** [comment]
They still haven't approved us.

**Comment by claucece** [comment]
This has the milestone of 'October' but it depends on whether or not we are accepted by the coverity scan.

**Comment by DrWhax** [comment]
I've sent them an e-mail on how we could assist in speeding up the process of being accepted. I got a reply that:

> The project is undergoing review for acceptance.

We'll see.

**Comment by DrWhax** [comment]
We got accepted!

**Comment by claucece** [comment]
Yeeess!!! Thanks @DrWhax

**Comment by claucece** [comment]
This is setup now!  I think @DrWhax that everything is now solved.

**Comment by claucece** [comment]
Added with badge and everything. Thanks @DrWhax
