### ISSUE TITLE
Sometimes the B prekey proofs are still wrong

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#162]
This is likely because of some uninitialized memory somewhere... It doesn't happen often though.

**Comment by olabini** [comment]
Actually, this seems to happen a lot right now - 60-70% of the time for me. I'll investigate.

**Comment by olabini** [comment]
Adding to this, libotr-ng DOES verify even the bad proofs...

**Comment by olabini** [comment]
OK, this has been fixed as of current master. The reason was because of sizeof used to generate keys - but after a recent refactoring sizeof returned the size of the pointer, instead of the buffer allocated. The fix was to not use sizeof in many of those places, to make the code more robust.

**Comment by claucece** [comment]
Ok, with the current code that I got, I get:

```
Encountered error when handling data: incorrect proof for prekey messages b key
```

**Comment by claucece** [comment]
My branch is at the latest commit from master on every library needed.

**Comment by olabini** [comment]
Really? I don't get that after doing the sizeof fixes I pushed

**Comment by claucece** [comment]
Yes.. I get it 4 out of 5 times.

**Comment by olabini** [comment]
Hmm. And you deleted absolutely everything, and you're sure libotr-ng has been installed?

**Comment by olabini** [comment]
Yeah, I get it now too. It doesn't happen as often as before though.

**Comment by olabini** [comment]
@claucece - can you try again with this fix?

**Comment by claucece** [comment]
Now it gets published. thanks.
