### ISSUE TITLE
Simplify and refactor state management

### ISSUE THREAD

**Issue by olabini** [twstrike/libotrv4#163]
This issue is about track everything related to the client orchestration, making sure state is read and available at the right times, and that publication happens when it should.

**Comment by olabini** [comment]
There are several issues that are closely connected to this one:
- #140 
- #139 
- otrv4/pidgin-otrng#87
- otrv4/pidgin-otrng#85
- otrv4/pidgin-otrng#82
- otrv4/pidgin-otrng#72
- otrv4/pidgin-otrng#13
- otrv4/pidgin-otrng#9
- otrv4/pidgin-otrng#8

**Comment by olabini** [comment]
This involves these objects:
- [x] Private long term key
- [x] Forging key
- [x] Client profile
- [x] Expired client profile (only loading etc)
- [x] Prekey profile
- [x] Expired prekey profile (only loading etc)
- [x] Prekey messages
- [x] Private material corresponding to prekey profile
- [x] Private material corresponding to prekey messages
- ~~Fingerprints~~ (for now, let's keep them outside of orchestration - the life cycle is different)
- ~~Instance tags~~ (for now, let's keep them outside of orchestration - the life cycle is different)

**Comment by olabini** [comment]
With the latest commits the private prekey profile material is now managed together with the prekey profile, so no need to manage it separately.

**Comment by olabini** [comment]
I would say this is done. At some point I'll tackle the v3 keys, instance tags and fingerprints, but I think I'll do that outside of this issue.

**Comment by claucece** [comment]
Thanks @olabini
