### ISSUE TITLE
Change ed448 basepoint to an EDdsa encoding

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#167]
Should be this base point:

14fa30f25b790898adc8d74e2c13bdfdc4397ce61cffd33ad7c2a0051e9c78874098a36c7373ea4b62c7c9563720768824bcb66e71463f6900

Mike Hamburg sent it by encoding them through the “ristretto” widget. We should check the correct zeros to add and put it on the auth.c file.

**Comment by olabini** [comment]
This is a quite tricky issue - thus why it's important @claucece does it, to make sure it's done properly.
