### ISSUE TITLE
Refactor the whole prekey client file

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#178]

**Comment by olabini** [comment]
I'll start work on this. It needs to be coupled with sorting out some of the other problems related to prekey servers etc.

**Comment by olabini** [comment]
So, this is connected to the pidgin plugin Prekey refactoring. It's pretty big and I feel a bit uncomfortable doing all this stuff in one guy, so the approach I'll use is to rename all old prekey client functions in libotr-ng and pidgin-otrng, but they will be left to work. Then I'll start implementing the new functionality, and finally start moving over all the work.

**Comment by olabini** [comment]
This is finally done!
