### ISSUE TITLE
Correct fingerprint generation

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#195]
It should include the 'forging key' as well, as detailed in the spec.

**Comment by olabini** [comment]
It's probably a good idea to do this at the same time as fixing up the ratchet initialization, since it will touch similar code. Have we defined in the spec how the fingerprint will be done, with the forging key?

**Comment by claucece** [comment]
Yes, agreed @olabini 

> Have we defined in the spec how the fingerprint will be done, with the forging key?

Yes, it is changed.

**Comment by olabini** [comment]
Great

**Comment by claucece** [comment]
Apart from checking some TODOs (that I'll tomorrow with @olabini ), this is basically done.
