### ISSUE TITLE
Error managing

### ISSUE THREAD

**Issue by tdruiva** [twstrike/libotrv4#2]
- [x] How we are managing errors? 
- [x] Is it protected, to not leak information?
- [x] Is it standard around our code?
- [x] How good it is defined in the spec?
- [x] Check bools
- [x] Check normal error: success and failures
- [x] Check all paths, specially the discard on instance tags. 
- [x] Check bools and otrv4 errors: use 1 or 0?

**Comment by claucece** [comment]
Closed on a39fd8d5b9674fdd7e11e293f9bf00de2215a560
