### ISSUE TITLE
Git master build broken on Arch Linux

### ISSUE THREAD

**Issue by ghost** [twstrike/libotrv4#202]
Hi, I'm not entirely sure this issue is with libotr-ng or pidgin-otrng, but recently I'm seeing the below when starting pidgin:

```
$ pidgin --login
pidgin: prekey_manager.c:1038: otrng_prekey_has_server_identity_for: Assertion `domain' failed.
Aborted (core dumped)
```
Seemingly, the libotr-ng build from git (via Arch PKGBUILD) is semi-broken.
Full build log: https://gist.github.com/glitsj16/cc8570e971baeedef60c8f63a88bda4d
```
...
/usr/include/glib-2.0/glib/gmacros.h:312:39: error: ISO C does not support ‘__FUNCTION__’ predefined identifier [-Wpedantic]
...
```

OS: Arch Linux
$ pacman -Q glib2 libotr-ng pidgin-otrng
glib2 2.60.0-1
libotr-ng-git 2782.97a6306b-1
pidgin-otrng-git 608.83242bc-1

**Comment by ghost** [comment]
Update: after clearing the pidgin profile and starting from scratch the issue is gone. Seemingly the glib2 related build error isn't breaking anything. Sorry for the noise.

**Comment by claucece** [comment]
Thanks for the issue! Glad you solved it :)
