### ISSUE TITLE
Be consistent with scalar serialization

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#21]
This includes at least:

- [x] change the `SNIZKPK` to use the `SCALAR` and not `MPI` (spec and implementation),
- [x] change all `SMP` messages to use the `SCALAR` type and not `MPI` (spec and implementation),

From: https://github.com/twstrike/libotrv4/commit/9302e159f8bc72fc42dd286f36d2118feaa93196#commitcomment-22181306

**Comment by claucece** [comment]
Done on 08445113d43042d9f03004891a7b8617ee420f81
