### ISSUE TITLE
Support stable releases of libgcrypt for Debian and Fedora

### ISSUE THREAD

**Issue by rosatolen** [twstrike/libotrv4#22]
Currently, our libotrv4 library requires a version of libgcrypt (1.7.6) that is higher than the stable versions that we can get from package managers on Debian and Fedora. We depend on 1.7 because we use constants like GCRY_MD_SHA3_512 that are defined in versions of libgcrypt higher than 1.6.9. 

Debian jessie (stable) supports a patched version of libgcrypt called: 1.6.3-2+deb8u2. 
Fedora 25 (stable) supports the version: 1.6.6-1.

If we intend to support these stable releases for major linux distributions, we will need to use an additional library that provides SHA3 functions and constants.

**Comment by claucece** [comment]
We are no longer using SHA3 from libgcrypt. Nevertheless, libgcrypt 1.8 comes with a some important [bug fixes](https://lists.gnupg.org/pipermail/gnupg-announce/2017q3/000410.html). Right now, we are cheking for v 1.8 but allowing 1.6 or newer versions.

**Comment by claucece** [comment]
Unless it is not enough, closing this issue on 10c52e49d4a167e566cd95bb8edea451be4c33c3 Will reopen if needed.
