### ISSUE TITLE
Allow generating v3 and v4 long term keys independently

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#26]
The current UI only shows the fingerprint for the OTRv4 long-term key, and the generate button is only enabled if the OTRv4 key is missing.

**Comment by claucece** [comment]
For the moment, please, don't look at this issue. It should be moved once we move the work to the pidgin plugin.

**Comment by claucece** [comment]
I'm closing this as this is of the pidgin plugin.
