### ISSUE TITLE
How should we communicate v3 + v4 long-term keys (and fingerprints) to the user? 

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#27]
The OTRv4 long-term (public) key is published together with a user profile that's signed with the OTRv3 long-term (private) key.

Can we make use of this and simplify the UI? Can we omit OTRv4 fingerprint when there's a profile signed by a trusted OTRv3 key?

**Comment by olabini** [comment]
No, I don't think we should omit the OTRv4 fingerprint, since then we reduce the security of the connection to the security of the OTRv3 key - and the whole point of updating to modern algorithms and sizes is that the old OTRv3 signing is not strong enough anymore.

**Comment by claucece** [comment]
Moving this to the plugin work.
