### ISSUE TITLE
Generate the extra symmetric key

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#33]

**Comment by claucece** [comment]
Done on 2c8b9feeaa72622add6c6c41a9708d6c6b0be7c5

**Comment by juniorz** [comment]
Comparing to OTRv3:

Given `secbytes = MPI(s)`, sending / receiving uses keys:

`encA = SHA1(0x01 || secbytes)[0:16]` and `macA = SHA1(encA)`
`encB = SHA1(0x02 || secbytes)[0:16]` and `macB = SHA1(encB)`

Then the sender/receiver decides which pair to use based on who is higher.

And the extra symmetric key is `extra = SHA256(0xFF || secbytes)`

So **both the encryption keys and the extra symmetric key are derived from the same secret** (`secbytes`). 

In OTRv4, this is not true: **encryption keys are derived from the chain key, and the extra symmetric key is derived from the `K` directly** (which is comparable to `secbytes` in OTRv3).
