### ISSUE TITLE
Client Profile API

### ISSUE THREAD

**Issue by tdruiva** [twstrike/libotrv4#4]
To create an API to generate and publish Client Profile.

**Comment by claucece** [comment]
For a mode where online and offline are accepted, the same Prekey Server can be used. For a mode with no offline, we need to define how to publish.

**Comment by olabini** [comment]
I think we can still use the Prekey Servers as the standard for this - but maybe in XMPP exposed under a different service name.

**Comment by claucece** [comment]
@olabini ok :)

**Comment by claucece** [comment]
This intersects with #98
