### ISSUE TITLE
Error handling for the Dakez

### ISSUE THREAD

**Issue by natalieesk** [twstrike/libotrv4#7]

**Comment by natalieesk** [comment]
The happy path is completed plus some error scenarios

**Comment by juniorz** [comment]
The sad path includes:
- [x] Receive Identity Message while on state WAITING_AUTH_I (#19)
- [x] Add test for "Receive Identity Message while on state WAITING_AUTH_R":
   - [x] When you are the lower 
   - [x] When you are the higher
- [x] Add test for "Receiving an Auth-R message while NOT on state WAITING_AUTH_R"
- [x] Add test for "Receiving an Auth-I message while NOT on state WAITING_AUTH_I"

**Comment by claucece** [comment]
Closed on ab3d55d01a6e35fe14a56b94b4378292f7242177
