### ISSUE TITLE
Correctly profile with GProf

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#75]
GProf is a tool for profiling.  It was tried to be introduced on the library on several occasions without any success:

https://github.com/otrv4/libotr-ng/commit/7171804449c39d878478da6bbdc148541fb6d016
https://github.com/otrv4/libotr-ng/commit/45350d19e2b9df57cf33f7efc7c421e084d07d15

We should try to use it (of course, if we want to have profiling).

**Comment by olabini** [comment]
What does this story mean?

**Comment by claucece** [comment]
This story is part of `LibOTRv4 API` project, for which I haven't putted the description as, as said, we are working over `Full OTRv4 flow #2` project. I'll update the description right now. Thanks for notifying.

**Comment by claucece** [comment]
@olabini The description has been updated ;)

**Comment by olabini** [comment]
This works fine now. In order to try it, just do `./configure --enable-gprof` and then `make profile`

**Comment by claucece** [comment]
Thanks @olabini This is just a 'won't work for MAC' ;)

**Comment by claucece** [comment]
So, yeah, just to add up to this: apparently, there is no way of installing gprof on MAC as right now.

**Comment by olabini** [comment]
=( that's sadface.
