### ISSUE TITLE
Don't use global variables or remove them

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#84]
## Why

A library should be sufficiently secure in its C handling. 

## Reference

Check [Global Variables Are Bad](http://wiki.c2.com/?GlobalVariablesAreBad)

## Tasks
- [x] Find where global variables are used and remove them.

## Open questions

None

**Comment by olabini** [comment]
I'll take a quick look at this

**Comment by olabini** [comment]
OK, so we had three places with globals in them (all of them static, so not really global).
The first was in test_messaging, that was doing some stuff with callbacks. I felt the APIs it was testing should be rethought, so I removed that test for now - it wasn't actually testing anything.
The second is in dh.c. This is caching of large MPIs. I don't see an obvious way of getting rid of them, without causing a bunch of trouble - and it's very harmless.
The final place is in otrng.c - it checks whether the OTRv3 library has been initialized yet or not. This also feels harmless.

I vote we close this issue now. Thoughts?

**Comment by claucece** [comment]
@olabini Thanks! Ok. I'll add this another test situation to issue #101 . Thanks!
