### ISSUE TITLE
Check for NULL dereferencing 

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#85]
## Why

A library should be sufficiently secure in the ways it is written. 

## Reference

[Null pointer](https://en.wikipedia.org/wiki/Null_pointer)

## Tasks
- [ ] Check that pointers do not NULL dereference.

## Open questions

None.

**Comment by olabini** [comment]
Is this story that we should go through and make sure we haven't any places where this happens, or something else?

**Comment by claucece** [comment]
> Is this story that we should go through and make sure we haven't any places where this happens

Yes.

**Comment by claucece** [comment]
This is something already addressed with the introduction of the address sanitizer and clang tidy. The places where this should change are marked as 'sanitizer', as a TODO.
