### ISSUE TITLE
Fix code coverage

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#90]
As reported by @deniscostadsc , this shows up when running `make coverage-check` with the coverage flag on some os:

`lcov: ERROR: no valid records found in tracefile libotr-ng-0.0.1-coverage.info.tmp`

Seems like an error with lcov... but might be worth looking into it. 

This works on the travis machines.

Thanks @deniscostadsc

**Comment by olabini** [comment]
I can't reproduce this either. I think this will have to be checked by someone that actually has the problem

**Comment by olabini** [comment]
This doesn't happen anymore - there was a lcov/gcov difference in the file formats they used, and Fedora 28 didn't have the right version for a while. With lcov upgrade to 1.13.4, this works as expected. For reference, this is where we are:
```
Overall coverage rate:
  lines......: 98.5% (3943 of 4003 lines)
  functions..: 99.4% (170 of 171 functions)
```

**Comment by claucece** [comment]
Thanks!

**Comment by olabini** [comment]
Turns out it's not done yet - we are not capturing for most files, for some reason.

**Comment by olabini** [comment]
OK, now it's fixed. If you still get lots of warnings about writing past the end of the file, or records of wrong length and things like that, it's because the lcov version is too old.

**Comment by claucece** [comment]
Thanks @olabini
