### ISSUE TITLE
Match variable names to those over the spec

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#92]
## Why

A library should use the same variable names as the OTRv4 specification or the ones that make sense.

## Reference

The OTRv4 specification.

## Tasks
- [ ] Check that all variable names are consistent with the OTRv4 spec.

## Open questions

None.

## Notes

If needed variable names can change on the OTRv4 spec.

See the UPDATE.

**Comment by olabini** [comment]
Is this the case even when variable names in the specification uses upper case or other things that go against our C style guide?

My proposal is that we follow C style first, and OTRv4 spec names second.

**Comment by claucece** [comment]
@olabini 

>Is this the case even when variable names in the specification uses upper case or other things that go against our C style guide?

When I mean the variable name, I'm talking about the name itself regardless of the written format on the OTRv4 spec (uppercase, Camel Case). The name should follow the name of the OTRv4 spec, and the written format of it should follow our style guide. ;)

**Comment by claucece** [comment]
UPDATE: after thinking about this, it will be good to follow the spec variable names only when they are sufficiently clear for use to do. Nevertheless, there should be congruency between the spec and the library.
