### ISSUE TITLE
Let all declarations be at the head of the block

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#93]
## Why

A library should be sufficiently useful and clear in the ways it is written. 

## Reference

21st Century C, Chapter 7, "Let declarations Flow"

## Discussion

All declarations can be at the head of the block or let them happen as needed.

## Tasks
- [ ] Discuss if we have declarations at  head of the block or let them happen as needed.

## Open questions

- The issue itself

**Comment by olabini** [comment]
In most cases, our functions shouldn't be large enough that this causes a big difference.
