### ISSUE TITLE
Should we use switch?

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#94]
## Why

A library should be sufficiently useful and clear in the ways it is written. 

## Reference

21st Century C, Chapter 7, "switch"

## Discussion

Should be use switch? Are if and else easier to read?

## Tasks
- [ ] Discuss if we use switch.

## Open questions

- The issue itself

**Comment by olabini** [comment]
I personally think switches are fine to use, in some circumstances.

**Comment by claucece** [comment]
@olabini Yeah... but maybe on some places we can simplify its use.

**Comment by olabini** [comment]
Oh yeah, absolutely. We should obviously strive to write as clear and simple code as possible!

**Comment by olabini** [comment]
I have gone through and reviewed all the switches in the current code base. I would argue that they are all fine from a readability standpoint, and I feel comfortable going forward with what we have. Let's keep our eyes on it - but I think we can close this issue.
