### ISSUE TITLE
Remove some values from the Prekey message

### ISSUE THREAD

**Issue by claucece** [twstrike/libotrv4#99]
## Why

As we are currently implementing the revision number 2 of the OTRv4 specification, we need to include a consistent way of using prekey messages.

## Reference

Please, refer to the "Prekey Message" section of the OTRv4 spec.

## Tasks
- [x] Remove User Profiles from the Prekey Message.
- [x] Make the Non-Interactive DAKE use these prekey messages, user profiles and prekey profiles separately.

## Depends on

Issue #78 

## Open questions
None.

**Comment by claucece** [comment]
@juniorz Maybe related to what you are doing?

**Comment by juniorz** [comment]
Yeah, I guess the "Make the Non-Interactive DAKE use these prekey messages, user profiles and prekey profiles separately" was what I was planning to do today.

**Comment by juniorz** [comment]
This was also done as part of #68.
